### ISSUE TITLE
Implement Linux support

### ISSUE THREAD

**Issue by randyburden** [AmbitEnergyLabs/Nano#23]
A long term goal will be to implement cross platform support for Linux.

**Comment by rrudduck** [comment]
I committed basic linux support into a branch called linux_support. Work was done in MonoDevelop so I need to clean things up a bit using VS, but the self-host demo is working. Next is making sure all the tests pass.

**Comment by randyburden** [comment]
This has now been merged and part of the [v0.11.0 release](https://github.com/AmbitEnergyLabs/Nano/releases/tag/v0.11.0).
