### ISSUE TITLE
Should swallow extra slashes in URL

### ISSUE THREAD

**Issue by bsschwa** [AmbitEnergyLabs/Nano#24]
Most websites allow extra slashes in URL and automatically redirect the user to the correct URL; however Nano throws a 404.  The problem arose because the proxy generator added a slash to the end of the base URL and also a slash at the beginning of the method address resulting in an extra slash.  EX: https://mywebsite.com//classname/methodname
![doubleslash](https://cloud.githubusercontent.com/assets/3469050/8193262/6c964588-1439-11e5-81cb-766fa25e32dd.png)
![singleslash](https://cloud.githubusercontent.com/assets/3469050/8193263/6cae173a-1439-11e5-9981-1e902d224d66.png)

**Comment by randyburden** [comment]
This was resolved in the following commit: c4b977fd5107b6049322ec01deb82ad340b3fef8
