### ISSUE TITLE
Proxy Generator: slash is added to end of BaseAPIURL and beginning of method address resulting in double slash in URL

### ISSUE THREAD

**Issue by bsschwa** [AmbitEnergyLabs/Nano#25]
![proxygeneratordoubleslash](https://cloud.githubusercontent.com/assets/3469050/8193497/c73122c8-143a-11e5-84a2-17b7a950f60b.png)

**Comment by randyburden** [comment]
This was resolved in the following commit: c4b977fd5107b6049322ec01deb82ad340b3fef8
