### ISSUE TITLE
Api Explorer deletes data typed in fields if you hide show row

### ISSUE THREAD

**Issue by revnique** [AmbitEnergyLabs/Nano#29]
Api Explorer deletes data typed in fields if you hide show row. you should only lose data if you click the clear button.

**Comment by randyburden** [comment]
I figured someone would eventually get annoyed by that behavior ;)

We'll get this and the accompanying pull request pulled into master within a day or two: https://github.com/AmbitEnergyLabs/Nano/pull/30

Thanks.
