### ISSUE TITLE
Error converting value null to type System.Nullable[System.Int64]

### ISSUE THREAD

**Issue by aaroncmoore** [AmbitEnergyLabs/Nano#54]
I am attempting to submit a null value to a long? parameter and I am receiving this error:

An error occurred converting the parameter named '<name>' and value 'null' to type System.Nullable`1[System.Int64] which is a required parameter for method '<name>' 

The object submission looks like this:
1.       field1:
null
2.    field2:
null
3.    field3:
43001
4.    field4:
OH
5.    field5:
D
6.    field6:
R

and the Nano method is:
public static ApiResponse CreateEnrollee(
            NanoContext nanoContext,
            string field1,
            string field3,
            string field4,
            string field5,
            string field6,
            long? field2 = null)
        {

field 1 works great passing null but is passed into a string parameter and field 2 throws the error when it is passed into long? field2.

Thanks.

**Comment by randyburden** [comment]
Is the string "null" being passed? If so the string "null" is not the same as null. The lack of sending the parameter would result in the expected behavior. I also believe sending a blank / empty string results in the expected behavior as well but I would need to confirm. Let me know your thoughts?

**Comment by aaroncmoore** [comment]
While I can say that the value being submitted is null, I'm not 100% that it is being passed as the null type.  However, since the string value is receiving the same null type properly and not the string 'null', and form data that is passed as string should have the double quotes around it, I believe the null type is being passed.

**Comment by aaroncmoore** [comment]
I found the issue in the proxy server.  In some cases it is taking null and converting it to the string 'null'.  Why this is only happening some of the time, I am not certain.  For now I have changed this code in the proxy server:

if (typeof data === "object" && data != null ) {
           for (var propertyName in data) {
               if (data.hasOwnProperty(propertyName)) {
                   var value = data[propertyName];
                   if (typeof value === "object") {
                       value = JSON.stringify(value);
                   }
                   queryString += (queryString.length === 0 ? "" : "&") + propertyName + "=" + encodeURIComponent(value); 
               }
           }
       }

to this:

                    if (typeof data === "object" && data != null ) {
                        for (var propertyName in data) {
                            if (data.hasOwnProperty(propertyName)) {
                                var value = data[propertyName];
                                if (value !== null && typeof value === "object") {
                                    value = JSON.stringify(value);
                                }
                                queryString += (queryString.length === 0 ? "" : "&") + propertyName + "=" + (value == null ? "" : encodeURIComponent(value)); 
                            }
                        }
                    }

I'll submit this issue as closed.
