### ISSUE TITLE
Proxy Generator won't generate proxies for "top level" objects with a Generic declaration.

### ISSUE THREAD

**Issue by matosconsulting** [AmbitEnergyLabs/Nano#58]
I have a service that returns a type of ApiResponse\<T\>, where T is a class specific to the API method. In this case, nano will output a proxy with expanded references to the namespaced object class, but it won't provide a proxy object for ApiResponse (or any of the nested/referenced classes).

Example:
```c#
namespace xxx.yyy.zzz
{
    public class ApiResponse<T>
    {
        public string ResponseCode;
        public string ResponseMessage;
        public T Result;
    }
}
```

Result:
```c#
        public static xxx.yyy.zzz.ApiResponse<Broker> Create(Broker broker, object correlationId = null)
        {
                ...
        }
```

(Notice the namespaced reference. Additionally, the output does not contain a definition for any version of ApiResponse - typed or generic.)

Interestingly, if I create a method that returns a nested object of ApiResponse like so:
```c#
        public static ApiResponse<ApiResponse<string>> GetTestApiResponse()
        {
            return new ApiResponse<ApiResponse<string>>();
        }
```
the proxy generator does seem to infer/figure out the type, and creates proxy objects for the nested/referenced types. (This is not a real world scenario - I was just trying to find a way to force nano to output the classes.)

```c#
public class ApiResponse`1
   {
       public String ResponseCode;
       public String ResponseMessage;
       public System.Collections.Generic.List<ApiError> Errors;
       public String Result;
   }
```

Is it possible to enhance the Nano Proxy Generator to also create proxy objects when Generics are involved?

**Comment by randyburden** [comment]
Fixed in https://github.com/AmbitEnergyLabs/Nano/commit/c00c8c8db6d2c663790517813d7599fa1086717d

This change will soon be released in v0.15.0
