### ISSUE TITLE
Inconsistent BaseApiUrl in Generated ApiProxy files

### ISSUE THREAD

**Issue by traviswaldorf** [AmbitEnergyLabs/Nano#69]
The index.html files generate a different baseApiUrl for the Javascript and C# generation. The code for Javascript generation has the expected token of {{BaseUrl}}, but the code for C# generation has a hard coded default value and doesn't reference what is configured.

**Comment by randyburden** [comment]
Using the [Nano ApiExplorer Demo](http://nano-1.apphb.com/ApiExplorer/) as an example I just generated a [C#](http://nano-1.apphb.com/ApiExplorer/?GenerateCSharpProxy=True) and [JavaScript](http://nano-1.apphb.com/ApiExplorer/?GenerateJavascriptProxy=True) proxy. *Note that the demo site is using the soon to be released Api Explorer v0.9.0 but there are no changes related to the C# or JavaScript proxy generators between v0.8.0 and v0.9.0.

1. I don't see any issues with an "unexpected token of {{BaseUrl}}". Could you elaborate on this or provide an example of how to reproduce this error.
2. I do see that the JavaScript proxy uses the current URL the proxy generator is being hosted from and how the C# generator is just using a hard-coded value. 
  1. Neither of these values are meant to be used as is. The intention is for the client ( whatever app is using these proxies ) on page load and/or application startup to set these values. I can see an argument for setting these base urls to a string such as "https://PleaseSetThisBaseUrlOnStartup" or something similar. =)

Let me know your thoughts and/or what you want accomplished.
