### ISSUE TITLE
C# Proxy generator doesn't correctly handle List<T>

### ISSUE THREAD

**Issue by bsschwa** [AmbitEnergyLabs/Nano#7]
When generating a proxy for a method that has a return type of "List<AnyType>" the result is "List`1"
![correctlist](https://cloud.githubusercontent.com/assets/3469050/8044532/fd2c0440-0df2-11e5-8c02-8eb03aff9feb.png)

![image](https://cloud.githubusercontent.com/assets/3469050/8044538/051ecaa2-0df3-11e5-8fe2-89b15cab1aef.png)

**Comment by randyburden** [comment]
This should be resolved with the following commit of version 0.3.0: bd46c7dcde7e69cf6ead48a6b8e2f0ef838a5465
